#include "stdafx.h"
#include "SolarSystemResources.h"

/// AUTOGENERATED METHODS ///

int SolarSystemResources::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int SolarSystemResources::Release() {
	return Simulator::cStrategy::Release();
}

const char* SolarSystemResources::GetName() const {
	return "RattlerSpore::SolarSystemResources";
}

bool SolarSystemResources::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool SolarSystemResources::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute SolarSystemResources::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void SolarSystemResources::Initialize() {
	
}

void SolarSystemResources::Dispose() {
	
}

void SolarSystemResources::Update(int deltaTime, int deltaGameTime) {
	
}